### ISSUE TITLE
mapped field value not available in action contents using YAML

### ISSUE THREAD

**Issue by dnagirl** [fsi-open/datagrid-bundle#53]
I am using YAML to config my grid. I have an action which toggles the 'pause' state of a row. The icon of the action button has to vary depending on the current 'pause' state. Here is the current config of the grid:

```
columns:
  id:
    type: number
    options:
      label: Identity
  description:
    type: text
  actionStatus:
    type: text
  isNotPaused:
    type: boolean
    options:
      label: Ready
  pausetoggle:
    type: action
    options:
      label: ''
      field_mapping: [pauseIcon, id]
      actions:
        toggle:
          route_name: task_pausetoggle
          parameters_field_mapping: {'id':id}
          url_attr:
            class: 'btn btn-default btn-sm'
            title: 'toggle pause state'
          content: '<i class="%pauseIcon%"></i>'
```

I have tried the following variations for the action `content`:

`content: '<i class="%pauseIcon%"></i>'`
`content: '<i class="pauseIcon"></i>'`
`content: '<i class="value.pauseIcon"></i>'`
`content: '<i class="%value.pauseIcon%"></i>'`

and some others.  All output the literal string rather than the interpolated one.  What is the correct syntax? Or do I have to use a different method?
